### ISSUE TITLE
Template error: ERROR: Include directive failed 

### ISSUE THREAD

**Issue by ran-codes** [jimjam-slam/sverto#15] opened 2023-04-17 18:53 UTC
Hi thanks for making this awesome quarto extension!

I am facing similar issues to #11 but I didn't want to comment on that issue as you guys having quite a deep technical conversation there. I saw there was a PR fixing this and then i just tried but facing same error. Details below

- initialized a template with `quarto use template 360-info/sverto` and ran`npm i`, deleted the docs folder 
- you can find code here: https://github.com/ran-codes/sverto-test/tree/main/april-17
- ran `quarto render` ( I am Quarto v1.2.475)
- See this error
![image](https://user-images.githubusercontent.com/45013044/232583306-f2c346d3-d823-4e4a-91da-8c1ce332667c.png)

Thanks for your help and lmk if I should close and just follow #11

**Comment by jimjam-slam** [comment] 2023-04-17 23:43
No worries, @ran-codes! This could actually be a separate error if it's failing to find Quarto's internal version of Deno.

Are you able to try [upgrading to Quarto 1.3?](https://quarto.org/docs/get-started/) I'm not 100% sure that Sverto works with 1.2 (I should add a minimum Quarto version of the extension manifest!).

**Comment by jimjam-slam** [comment] 2023-04-23 08:06
Also, if you could try upgrading to the new version of Sverto (released today), that would also be great!

**Comment by ran-codes** [comment] 2023-04-27 15:34
hello! I upgraded to quarto 1.3, used the new sverto (0.2), then run `npm i` but still get error (see snip below). You can find this project [here if it is helpful](https://github.com/ran-codes/sverto-test/tree/main/april-27).

![image](https://user-images.githubusercontent.com/45013044/234912437-74f3bac7-cca5-41ae-8780-50f9660ff939.png)

Thanks for your help! (really excited to be able to do Svelte in quarto 😄 )

**Comment by jimjam-slam** [comment] 2023-04-27 23:26
Thanks for the repro, @ran-codes! I'll take a look as soon as I can!

**Comment by jimjam-slam** [comment] 2023-04-27 23:43
Out of interest, do you get this error when you try to render Quarto projects that _don't_ include Sverto? From that screenshot, it seems like the pre-render script is having trouble locating Deno (which comes with Quarto).

if you can run regular projects that don't have a pre-render script, I'll put together a minimal pre-render script to test this theory (maybe it's just that Deno isn't properly being exposed to the pre-render script for Windows users).

**Comment by ran-codes** [comment] 2023-04-29 02:15
### Regular Quarto project

![image](https://user-images.githubusercontent.com/45013044/235279027-b7032a77-f8f8-4d4e-baf8-445576972908.png)

**Comment by jimjam-slam** [comment] 2023-05-15 00:22
Hey @ran-codes, sorry for the delay here! I'm able to clone, install and render your demo repo without a problem:

![image](https://github.com/360-info/sverto/assets/6520659/7768b788-06d2-4725-aa6d-ab3ae5fef081)

That doesn't mean this is your fault, of course! I'm testing on a Mac, and I'm wondering if there's a platform difference that is causing Deno not to be found on Windows.

I'll try to organise some Windows testing to try and get to the bottom of this!

**Comment by ran-codes** [comment] 2023-05-15 12:39
Thanks again!! please let me know if there is anything you need help with. happy to contribute time to this extension in any way.

**Comment by jimjam-slam** [comment] 2023-05-16 03:04
@ran-codes I'm just going to try adding a simpler pre-render script to your "vanilla" (non-Sverto) Quarto project to see if we can isolate this as a Quarto problem!

I've [made a pull request](https://github.com/ran-codes/sverto-test/pull/1) on your sample project that includes the test. Could you please run `quarto render` on the April 28 script including my test script and see if it reports a success?

You should see (the specific version aside):

```
Test script: attempting to get Deno version...
Current Deno version 1.28.2
Test script: success!

pandoc 
  to: html
  output-file: example.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Svelte example
  author: 'James Goldie, 360info'
  date: last-modified
  
Output created: _site/example.html
```

**Comment by ran-codes** [comment] 2023-05-16 12:30
Thanks. After merging the PR I ran the  vanilla (non-Sverto) Quarto project. It worked (see log below)!


```
PS D:\git\sverto-test\april-28-vanilla-test> quarto render
WARNING: Specified QUARTO_DENO does not exist, using built in deno
Test script: attempting to get Deno version...
Current Deno version 1.25.2
Test script: success!      

pandoc 
  to: html
  output-file: example.html      
  standalone: true
  section-divs: true
  html-math-method: mathjax      
  wrap: none
  default-image-extension: png   
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Svelte example
  author: 'James Goldie, 360info'
  date: last-modified

Output created: _site\example.html
```

**Comment by jimjam-slam** [comment] 2023-05-16 23:53
I won't push a test to the PR I made myself, but I think a helpful thing to do would be to firstly, in the PowerShell terminal where you know you can run `npm install`,

* Run `Get-Command npm` to see where npm is;
* Run `$Env:Path` to verify that npm is on the system path in your PS terminal

Then, in `test.ts`:

* Add `console.log("Path in Quarto's Deno: ", Deno.get.env("Path"))`

The goal here is to verify that the path inside the pre-render script is the same as the one in your terminal and that Deno can find npm (if not, I might need to think more carefully about how to find npm!).

**Comment by ran-codes** [comment] 2023-05-17 22:22
## searching for npm in powershell

```
PS D:\git\sverto-test\april-28-vanilla-test> Get-Command npm
>> $Env:Path

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     npm.cmd                                            0.0.0.0    C:\Program Files\nodejs\npm.cmd
C:\Python311\Scripts\;C:\Python311\;C:\Python310\Scripts\;C:\Python310\;C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python39\Scripts\;C:\Python39\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\ranli\AppData\Roaming\Python\Python38\Scripts;C:\Program Files\R\R-4.0.1\bin\x64;C:\Program Files\MiKTeX\miktex\bin\x64\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft\Azure Functions Core Tools\;C:\Program Files\nodejs\;C:\Program Files\Git\bin;C:\Users\ranli\AppData\Roaming\Python\Python311\Scripts;C:\Program Files\Pandoc\;D:\Program Files\SAS\SASFoundation\9.4\core\sasexe;D:\Program Files\SAS\SASFoundation\9.4\ets\sasexe;D:\Program Files\SAS\Secure\ccme4;D:\Program Files\SAS\SASFoundation\9.4\core\sasext;C:\Users\ranli\AppData\Local\Programs\Quarto\bin;C:\Users\ranli\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\ranli\AppData\Local\Programs\Python\Python38\;C:\Users\ranli\AppData\Local\Microsoft\WindowsApps;C:\Users\ranli\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\R\R-4.0.1\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\bin;C:\Users\ranli\AppData\Local\Microsoft\WindowsApps;C:\Users\ranli\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\ranli\.dotnet\tools;C:\Users\ranli\AppData\Roaming\TinyTeX\bin\win32;C:\Users\ranli\AppData\Roaming\npm;C:\ProgramData\ranli\GitHubDesktop\bin;C:\Users\ranli\AppData\Local\GitHubDesktop\bin;C:\Users\ranli\.deno\bin
````

### Check for npm in pre-render script 

- [x] Added  `console.log("Path in Quarto's Deno: ", Deno.env.get("Path"))` to test.ts
- [x] log after quarto render is shown below

```
PS D:\git\sverto-test> cd .\april-28-vanilla-test\
PS D:\git\sverto-test\april-28-vanilla-test> quarto render
WARNING: Specified QUARTO_DENO does not exist, using built in deno
Test script: attempting to get Deno version...
Current Deno version 1.25.2
Test script: success!
Path in Quarto's Deno:  C:\Python311\Scripts\;C:\Python311\;C:\Python310\Scripts\;C:\Python310\;C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python39\Scripts\;C:\Python39\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program 
Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\ranli\AppData\Roaming\Python\Python38\Scripts;C:\Program Files\R\R-4.0.1\bin\x64;C:\Program Files\MiKTeX\miktex\bin\x64\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft\Azure Functions Core Tools\;C:\Program Files\nodejs\;C:\Program Files\Git\bin;C:\Users\ranli\AppData\Roaming\Python\Python311\Scripts;C:\Program Files\Pandoc\;D:\Program Files\SAS\SASFoundation\9.4\core\sasexe;D:\Program Files\SAS\SASFoundation\9.4\ets\sasexe;D:\Program Files\SAS\Secure\ccme4;D:\Program Files\SAS\SASFoundation\9.4\core\sasext;C:\Users\ranli\AppData\Local\Programs\Quarto\bin;C:\Users\ranli\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\ranli\AppData\Local\Programs\Python\Python38\;C:\Users\ranli\AppData\Local\Microsoft\WindowsApps;C:\Users\ranli\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\R\R-4.0.1\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\bin;C:\Users\ranli\AppData\Local\Microsoft\WindowsApps;C:\Users\ranli\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\ranli\.dotnet\tools;C:\Users\ranli\AppData\Roaming\TinyTeX\bin\win32;C:\Users\ranli\AppData\Roaming\npm;C:\ProgramData\ranli\GitHubDesktop\bin;C:\Users\ranli\AppData\Local\GitHubDesktop\bin;C:\Users\ranli\.deno\bin
POST PATH!

pandoc 
  to: html
  output-file: example.html
  standalone: true
  section-divs: true       
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Svelte example
  author: 'James Goldie, 360info'
  date: last-modified

Output created: _site\example.html
```

**Comment by jimjam-slam** [comment] 2023-05-18 00:46
Mmm, okay! It's definitely on the PATH when Deno runs (although that isn't a guarantee that it's in the PATH for the process that Deno spawns using `Deno.run()`. I've just pushed a couple of other tests as PRs (https://github.com/ran-codes/sverto-test/pull/2, https://github.com/ran-codes/sverto-test/pull/3).

One tests feeding the `PATH` from Sverto's script into `Deno.run` manually, in the hopes that `Deno.run()` can use it to find npm.

The other tries running npm inside a shell, since that should also bring your PATH in.

If either of those work, I'll look at implementing them for Windows users!

**Comment by jimjam-slam** [comment] 2023-05-18 23:19
Oh! Do you know if one test or the other worked? I hadn't intended that you use both!

As for the second error, `.sverto/.sverto-outdir` is a file created before we get to Svelte compilation—it just records where the output is going. Can you confirm that this file is in the `.sverto` directory when you hit this error?

if so, it sounds like we're having a problem resolving this relative file path on Windows 🤔 The problem is here, in `rollup.config.js`:

https://github.com/360-info/sverto/blob/7507efec0c06b82f3c23b02b95144f9b0e21635a/_extensions/sverto/rollup.config.js#LL13C1-L16C1

We could try prefixing `"./"` in case Windows needs that for a relative path. Are you able to change those two lines in your copy of the file to:

```js
const quartoOutDir = fs.readFileSync('./.sverto/.sverto-outdir', 'utf8');

const svelteImportListPath = './.sverto/.sverto-imports';
```

Hopefully that's enough! (Although we also feed in a list of file paths, and it could be that those need to change too. But at least if we get past these lines, we know it's the problem!)

**Comment by jimjam-slam** [comment] 2023-05-18 23:27
A quick search of [Rollup's configuration docs](https://rollupjs.org/configuration-options) suggests that relative paths ought to start with `./`, so this could well be the problem!

**Comment by ran-codes** [comment] 2023-05-19 13:53
# Error logs

### Test: wrap npm call in cmd https://github.com/ran-codes/sverto-test/pull/3

still error: see log

```
PS D:\git\sverto-test\april-27> quarto render
Error running filter C:\Users\ranli\AppData\Local\Programs\Quarto\share\filters\init\init.lua:
cannot open C:\Users\ranli\AppData\Local\Programs\Quarto\share\filters\init\init.lua: No such file or directory

> svelte-app@1.0.0 build
> rollup -c D:\git\sverto-test\april-27\_extensions\360-info\sverto\rollup.config.js

[!] Error: ENOENT: no such file or directory, open '.sverto/.sverto-outdir'
Error: ENOENT: no such file or directory, open '.sverto/.sverto-outdir'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.<anonymous> (D:\git\sverto-test\april-27\_extensions\360-info\sverto\rollup.config.js:23:25)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.require.extensions.<computed> [as .js] (D:\git\sverto-test\april-27\node_modules\rollup\dist\shared\loadConfigFile.js:621:20)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at loadConfigFromBundledFile (D:\git\sverto-test\april-27\node_modules\rollup\dist\shared\loadConfigFile.js:631:42)


ERROR: Include directive failed.
  in file D:\git\sverto-test\april-27\example.qmd,
  could not find file D:\git\sverto-test\april-27\.sverto\example.qmd.

Error: Include directive failed.
  in file D:\git\sverto-test\april-27\example.qmd,
  could not find file D:\git\sverto-test\april-27\.sverto\example.qmd.
    at retrieveInclude (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:84148:23)
    at Object.directive (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:84184:15)
    at handleLanguageCells (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:57675:83)
    at async renderContexts (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:82666:45)
    at async renderFiles (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:86518:28)
    at async renderProject (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:86797:25)
    at async Command.fn (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:90853:32)
    at async Command.execute (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:8437:13)
    at async quarto (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:127539:5)
    at async file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:127557:9

```


## Test: manually feed path var to the run build script  https://github.com/ran-codes/sverto-test/pull/2

still error: see log

```
PS D:\git\sverto-test\april-27> quarto render
Error running filter C:\Users\ranli\AppData\Local\Programs\Quarto\share\filters\init\init.lua:
cannot open C:\Users\ranli\AppData\Local\Programs\Quarto\share\filters\init\init.lua: No such file or directory

> svelte-app@1.0.0 build
> rollup -c D:\git\sverto-test\april-27\_extensions\360-info\sverto\rollup.config.js

[!] Error: ENOENT: no such file or directory, open '.sverto/.sverto-outdir'
Error: ENOENT: no such file or directory, open '.sverto/.sverto-outdir'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.<anonymous> (D:\git\sverto-test\april-27\_extensions\360-info\sverto\rollup.config.js:23:25)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.require.extensions.<computed> [as .js] (D:\git\sverto-test\april-27\node_modules\rollup\dist\shared\loadConfigFile.js:621:20)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
PS D:\git\sverto-test\april-27> quarto render
Error running filter C:\Users\ranli\AppData\Local\Programs\Quarto\share\filters\init\init.lua:
cannot open C:\Users\ranli\AppData\Local\Programs\Quarto\share\filters\init\init.lua: No such file or directory
error: Uncaught NotFound: program not found
const compileStep = Deno.run({
                         ^
    at opRun (deno:runtime/js/40_process.js:33:16)
    at Object.run (deno:runtime/js/40_process.js:116:17)
    at file:///D:/git/sverto-test/april-27/_extensions/360-info/sverto/compile-imports.ts:10:26

ERROR: Include directive failed.
  in file D:\git\sverto-test\april-27\example.qmd,
  could not find file D:\git\sverto-test\april-27\.sverto\example.qmd.

Error: Include directive failed.
  in file D:\git\sverto-test\april-27\example.qmd,
  could not find file D:\git\sverto-test\april-27\.sverto\example.qmd.
    at retrieveInclude (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:84148:23)     
    at Object.directive (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:84184:15)    
    at handleLanguageCells (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:57675:83) 
    at async renderContexts (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:82666:45)
    at async renderFiles (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:86518:28)   
    at async renderProject (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:86797:25) 
    at async Command.fn (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:90853:32)
    at async Command.execute (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:8437:13)
    at async quarto (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:127539:5)
    at async file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:127557:9
```


### After prefixing rollup paths with `./` 

Error log:

```
PS D:\git\sverto-test\april-27> quarto render
Error running filter C:\Users\ranli\AppData\Local\Programs\Quarto\share\filters\init\init.lua:
cannot open C:\Users\ranli\AppData\Local\Programs\Quarto\share\filters\init\init.lua: No such file or directory
error: Uncaught NotFound: program not found
const compileStep = Deno.run({
                         ^
    at opRun (deno:runtime/js/40_process.js:33:16)
    at Object.run (deno:runtime/js/40_process.js:116:17)
PS D:\git\sverto-test\april-27> quarto render
Error running filter C:\Users\ranli\AppData\Local\Programs\Quarto\share\filters\init\init.lua:
cannot open C:\Users\ranli\AppData\Local\Programs\Quarto\share\filters\init\init.lua: No such file or directory

> svelte-app@1.0.0 build
> rollup -c D:\git\sverto-test\april-27\_extensions\360-info\sverto\rollup.config.js

[!] Error: ENOENT: no such file or directory, open './.sverto/.sverto-outdir'
Error: ENOENT: no such file or directory, open './.sverto/.sverto-outdir'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.<anonymous> (D:\git\sverto-test\april-27\_extensions\360-info\sverto\rollup.config.js:23:25)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.require.extensions.<computed> [as .js] (D:\git\sverto-test\april-27\node_modules\rollup\dist\shared\loadConfigFile.js:621:20)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at loadConfigFromBundledFile (D:\git\sverto-test\april-27\node_modules\rollup\dist\shared\loadConfigFile.js:631:42)


ERROR: Include directive failed.
  in file D:\git\sverto-test\april-27\example.qmd,
  could not find file D:\git\sverto-test\april-27\.sverto\example.qmd.

Error: Include directive failed.
  in file D:\git\sverto-test\april-27\example.qmd,
  could not find file D:\git\sverto-test\april-27\.sverto\example.qmd.
    at retrieveInclude (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:84148:23)
    at Object.directive (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:84184:15)
    at handleLanguageCells (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:57675:83)
    at async renderContexts (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:82666:45)
    at async renderFiles (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:86518:28)
    at async renderProject (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:86797:25)
    at async Command.fn (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:90853:32)
    at async Command.execute (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:8437:13)
    at async quarto (file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:127539:5)
    at async file:///C:/Users/ranli/AppData/Local/Programs/Quarto/bin/quarto.js:127557:9
```


# Troubleshootig:  init.lua?

I actually don't have this on my computer. Not sure its an issue 

![image](https://github.com/360-info/sverto/assets/45013044/3fb5611d-9e34-4bda-a7ec-2e6e27741905)

perhaps this create-imports.lua isn't running and not create the downstream .sverto folders? (my best guess haha)

**Comment by jimjam-slam** [comment] 2023-05-20 00:29
Well, `create-imports.lua` is the script that populates `.sverto`. If you can see files appearing in there (it gets created inside your project directory), it's definitely running!

**Comment by jimjam-slam** [comment] 2023-05-20 00:34
As far as `init.lua` goes, I'd have to defer to the Quarto devs—it could be that that filter gets puts there when you trigger a render, and that this is a red herring. Not sure tbh! 😅

**Comment by jimjam-slam** [comment] 2023-06-02 06:07
Hi @ran-codes, just a heads up that while I'm still working on this, Sverto is now hosted on my personal GitHub account, not @360-info's. Issues have migrated, and existing links should still work, so I don't expect anything to break. Just giving you a heads up!

**Comment by ran-codes** [comment] 2023-06-02 10:49
great. Thanks for the heads up! @jimjam-slam 🍰

**Comment by jimjam-slam** [comment] 2023-07-10 01:54
I've set up CI/CD for Sverto with GitHub Actions, so I can at least now reproduce this issue! 😅 

https://github.com/jimjam-slam/sverto/actions/runs/5503062472/jobs/10027892801

I'll make some changes on a development branch to see if I can drill into this more!

**Comment by jimjam-slam** [comment] 2024-03-17 09:14
Hey @ran-codes, just a heads up that I have a major refactor of Sverto coming down the pipe! It's in #20 and currently works on macOS and Linux (just polishing up the rough edges). However, I'm hitting the same problem trying to get rollup going from Windows. You can see the CI tests in the pull request. I believe it's the same root cause: executing an rpm script on Windows.

One thing that could be helpful is if you could test doing the quarto render from [Git Bash for Windows](https://git-scm.com/downloads) rather than PowerShell. If this is a syntax issue, hopefully using that shell can resolve it! However, I'll reach out to the Quarto team to see if they have any guidelines for this stuff too 😊

**Comment by jimjam-slam** [comment] 2024-03-20 23:37
@ran-codes, #20 is now working on Windows, provided you have Quarto pre-release 1.5.25 (released last week) or higher! It's on the `dev` branch. (There was a Quarto bug preventing Lua script execution.) Would love to hear how you go as I polish things up for a proper release!

Note that usage has changed in the new version: take a look at [the `README` in the `dev` branch](https://github.com/jimjam-slam/sverto/blob/dev/README.md) for instructions.

**Comment by jimjam-slam** [comment] 2024-05-12 23:33
Sverto v1.0.0 is now in `main` and works on Windows with Quarto >= 1.5.25 🥳

**Closed by jimjam-slam** 2024-05-12 23:33 UTC
Labels: bug

**Comment by ran-codes** [comment] 2024-05-13 21:10
thanks! looks awesome. Congratulation!!
